#!/usr/bin/env python3
#
# Generate fucking xorriso UUID

from random import randint

def gen_num(a, b):
    return str(randint(a, b))

def main():
  """I hate xorriso
  yyyyMMddhhmmsscc
  """
  print(gen_num(1970, 2999) + gen_num(10, 13) + gen_num(10, 31)
        + gen_num(10, 23) + gen_num(10, 59) + gen_num(10, 59)
        + gen_num(10, 99))

if __name__ == "__main__":
    main()
