#!/usr/bin/env bash
#
# Build an archiso
set -e

cfg='/var/arch9660/cfg'
idir='/var/arch9660/idir'
odir='/var/arch9660/odir'
imgdir='/var/arch9660/img'

# poshol nahui dolbaeb kotoriy pridumal pihat datu v uuid
[[ -v SOURCE_DATE_EPOCH ]] || printf -v SOURCE_DATE_EPOCH '%(%s)T' -1
printf -v iso_uuid '%(%F-%H-%M-%S-00)T' "${SOURCE_DATE_EPOCH}"
export SOURCE_DATE_EPOCH

cat "${cfg}/etc/pacman.conf" > /etc/pacman.conf
pacman -Sy arch-install-scripts mtools \
  xorriso dosfstools erofs-utils --noconfirm

mkdir -p "${idir}" "${odir}" "${imgdir}"
cp -RTa "${cfg}" "${idir}"
pacstrap -cG "${idir}" amd-ucode base bash-completion linux-zen \
  linux-firmware gptfdisk mkinitcpio mkinitcpio-archiso python \
  arch-install-scripts reflector btrfs-progs dosfstools iwd \
  iptables-nft less nano zram-generator &>/dev/null

# Configs
ln -sf /etc/pam.d/su "${idir}/etc/pam.d/su-l"
ln -sf /usr/share/zoneinfo/UTC "${idir}/etc/localtime"
ln -sf /usr/local/bin/y2ai "${idir}/usr/local/bin/arch-install"
sed -i "s/<UUID>/${iso_uuid}/" \
  "${idir}/boot/loader/entries/arch9660-zen.conf"
chmod -R 755 "${idir}/usr/local/bin"

date +'arch%d-%m-%y' \
  > "${idir}/etc/hostname"

chmod 400 "${idir}/etc/shadow"

# ESP
rm -f "${idir}/boot/amd-ucode.img"
bootsize="$(du -B1024 -s "${idir}/boot" | awk '{print $1}')"
espsize="$((bootsize + 512))"

mkfs.fat -F32 -S512 -R2 -v -f1 -s1 -b0 -n 'ESP9660' \
  --codepage=437 -C "${imgdir}/esp.img" "${espsize}"

mmd -i "${imgdir}/esp.img" \
  '::/loader' '::/loader/entries' \
  '::/EFI' '::/EFI/BOOT'

mcopy -i "${imgdir}/esp.img" \
  "${idir}/boot/"{vmlinuz-linux-zen,initramfs-linux-zen.img} \
  '::/'
mcopy -i "${imgdir}/esp.img" \
  "${idir}/usr/lib/systemd/boot/efi/systemd-bootx64.efi" \
  '::/EFI/BOOT/BOOTX64.EFI'
mcopy -i "${imgdir}/esp.img" \
  "${idir}/boot/loader/loader.conf" '::/loader'
mcopy -i "${imgdir}/esp.img" \
  "${idir}/boot/loader/entries/arch9660-zen.conf" '::/loader/entries'

# Cleanup
rm -rf "${idir}/"{boot,var/tmp,var/log,tmp}/* \
  "${idir}/var/cache/pacman/pkg/"* "${idir}/var/lib/pacman/sync/"* \
  "${idir}/usr/share/"{gtk-doc,gir-1.0,man} \
  "${idir}/usr/include" /usr/lib/lib{go,icudata}.* \
  "${idir}/usr/lib/firmware/"{nvidia,intel}
find "${idir}" \( -name '*.pacnew' \
  -o -name '*.pacsave' -o -name '*.pacorig' \) -delete
find "${idir}/var/lib/pacman" \
  -maxdepth 1 -type f -delete

# EROFS compressed img
mkfs.erofs -Efragments,dedupe,force-inode-extended,ztailpacking --quiet \
  -T0 -zlzma,109,dictsize=8388608 -C1048576 "${odir}/airootfs.erofs" "${idir}"

# ISO9660 file build
xorriso -no_rc -temp_mem_limit 1024m -as mkisofs -iso-level 2 -rational-rock \
  -volid 'ARCH9660' -appid 'arch9660' -preparer 'prepared by arch9660' \
  -publisher 'Arch9660 <https://github.com/nedorazrab0/arch9660>' \
  -append_partition 2 'C12A7328-F81F-11D2-BA4B-00A0C93EC93B' "${imgdir}/esp.img" \
  -appended_part_as_gpt -partition_offset 16 -no-pad \
  -output "${imgdir}/arch9660.iso" "${odir}"

blkid "${imgdir}/arch9660.iso"
