name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Build
       run: |
         docker pull archlinux
         docker run --name arch -dt --privileged archlinux:latest
         docker cp ./arch9660 arch:/var
         docker exec arch bash /var/arch9660/main
         docker cp arch:/var/arch9660/img/arch9660.iso .
         docker stop arch

     - name: SHA calculation
       run: |
         echo "sha=$(openssl sha256 ./arch9660.iso | cut -d ' ' -f2)" \
           | tee -a "${GITHUB_ENV}"

     - name: Releaseing
       run: |
         gh release delete iso --cleanup-tag -y || true
         echo "SHA256: \`${sha}\`" \
           | gh release create iso ./arch9660.iso -F -
       env:
         GH_TOKEN: ${{ github.token }}
