name: rls
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Build
       run: |
         docker pull archlinux:latest
         docker run --name arch -dt --privileged archlinux:latest
         docker cp ./arch9660 arch:/var
         docker exec arch bash /var/arch9660/test.sh
         docker stop arch
